@url_dev=http://localhost:3000/v1/api

### 1. Yêu cầu quên mật khẩu
POST {{url_dev}}/forgot-password
Content-Type: application/json

{
    "email": "admin@ticketrush.com"
}

### 2. Đặt lại mật khẩu mới (Lấy token từ Email hoặc DB)
# Thay :token bằng mã token nhận được
POST {{url_dev}}/reset-password/THAY_TOKEN_VAO_DAY
Content-Type: application/json

{
    "password": "newpassword123"
}
